# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fluent-grpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("fluent-grpc.proto", :syntax => :proto3) do
    add_message "fluent.grpc.LogRequest" do
      optional :tag, :string, 1
      optional :message, :string, 2
    end
    add_message "fluent.grpc.LogResponse" do
    end
  end
end

module Fluent
  module Grpc
    LogRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("fluent.grpc.LogRequest").msgclass
    LogResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("fluent.grpc.LogResponse").msgclass
  end
end
